<?php echo sfSympalContentToolkit::getContentRoutesYaml() ?>

<?php echo sfSympalContentToolkit::getRedirectRoutesYaml() ?>

homepage:
  url:   /
  param: { module: <?php echo sfSympalConfig::get('default_rendering_module', null, 'sympal_content_renderer') ?>, action: <?php echo sfSympalConfig::get('default_rendering_action', null, 'action') ?>, result_type: object, sympal_content_type: sfSympalPage, sympal_content_slug: home }
  class: sfDoctrineRoute
  options:
    allow_empty: true
    model:  sfSympalContent
    type:   object
    method: getContent


sympal_change_language_form:
  url:   /change_language
  param: { module: sympal_default, action: change_language }
  requirements:
    sf_method: [post]

sympal_change_language:
  url:   /change_language/:language
  param: { module: sympal_default, action: change_language }

sympal_change_edit_language:
  url:   /change_edit_language/:language
  param: { module: sympal_default, action: change_edit_language }

sympal_sitemap:
  url:   /sitemap.xml
  param: { module: sympal_default, action: sitemap, sf_format: xml }
  requirements:
    sf_format: [xml]


# Admin actions


sympal_content_types:
  class:                  sfDoctrineRouteCollection
  options:
    model:                sfSympalContentType
    module:               sympal_content_types
    prefix_path:          admin/content/types
    with_wildcard_routes: true

sympal_content_slots:
  class:                  sfDoctrineRouteCollection
  options:
    model:                sfSympalContentSlot
    module:               sympal_content_slots
    prefix_path:          admin/content/slots
    with_wildcard_routes: true

sympal_sites:
  class:                  sfDoctrineRouteCollection
  options:
    model:                sfSympalSite
    module:               sympal_sites
    prefix_path:          admin/sites
    with_wildcard_routes: true

sympal_redirects:
  class:                  sfDoctrineRouteCollection
  options:
    model:                sfSympalRedirect
    module:               sympal_redirects
    prefix_path:          admin/redirects
    with_wildcard_routes: true

sympal_content:
  class:                  sfDoctrineRouteCollection
  options:
    model:                sfSympalContent
    module:               sympal_content
    prefix_path:          admin/content/manage
    with_wildcard_routes: true

sympal_content_types_index:
  url:  /admin/content
  param: { module: sympal_content, action: content_types_index }

sympal_content_edit_slots:
  url:  /admin/content/:id/edit_slots
  param: { module: sympal_content, action: edit_slots }

sympal_content_create_type:
  url:    /admin/content/manage/create/:type
  param:  { module: sympal_content, action: create_type }

sympal_content_list_type:
  url:    /admin/content/manage/type/:type
  param: { module: sympal_content, action: list_type }