parameters:

  actions_extended.class:     sfSympalActions             # Acts as an extension of sfComponent

  site_manager.class:         sfSympalSiteManager                 # Manages the current site object
  
  slot_renderer.class:        sfSympalSlotRenderer                # Helps to render a slot

services:

  actions_extended:
    class:                    %actions_extended.class%
    shared:                   true

  site_manager:
    class:                    %site_manager.class%
    shared:                   true
    arguments:                [@sympal_configuration]
  
  slot_renderer:
    class:                    %slot_renderer.class%
    shared:                   false
    arguments:                [@sympal_configuration]


